### DISCUSSION TITLE
How to process the pipeline offline?

### DISCUSSION THREAD

**Discussion by fne2** [pyannote/pyannote-audio#1236] [Q&A]
Hi!

I'm new in using pretrained models and ml in general.
I wonder how I can process this code offline?

```python
from pyannote.audio import Pipeline
access_token = "TOKEN"
pipeline = Pipeline.from_pretrained('pyannote/speaker-diarization', use_auth_token=access_token)
```

Can anybody explain how I need to change the code?

I found out how to download the segmentation model, but I do not understand how it works with the `Pipeline`:

```python
from pyannote.audio import Model
from pyannote.audio import Inference
model = Model.from_pretrained('pytorch_model.bin')
inference = Inference(model, step=2.5)
output = inference('my.wav')
```
Thank you for any help!

EDIT:

So I figured it out with: https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/applying_a_pipeline.ipynb
One of my problems was that my relative file path didn't work, so I had to use an abspath.

```
pipeline:
  name: pyannote.audio.pipelines.SpeakerDiarization
  params:
    clustering: AgglomerativeClustering
    embedding: speechbrain/spkrec-ecapa-voxceleb
    embedding_batch_size: 32
    embedding_exclude_overlap: true
    segmentation: '/home/user/whisperAnnotate/speaker-diarization/pytorch_model.bin' #pyannote/segmentation@2022.07
    segmentation_batch_size: 32
```
