### ISSUE TITLE
ValueError: parameter 'segmentation_onset' does not exist - for custom pipeline 

### ISSUE THREAD

**Issue by laphang** [pyannote/pyannote-audio#1161]
when I run:
```
from pyannote.audio import Pipeline
pipeline = Pipeline.from_pretrained("speaker-diarization-config.yaml", use_auth_token=YOUR_TOKEN)
```
where `speaker-diarization-config.yaml` is the local customised pipeline file containing:
```
pipeline:
  name: pyannote.audio.pipelines.SpeakerDiarization
  params:
    segmentation: pyannote/segmentation@2022.07
    segmentation_step: 0.1
    segmentation_batch_size: 32
    embedding: pyannote/embedding
    embedding_exclude_overlap: True
    embedding_batch_size: 32
    clustering: HiddenMarkovModelClustering

params:
  segmentation_onset: 0.58
  clustering:
    covariance_type: diag
    threshold: 0.35
    single_cluster_detection:
      quantile: 0.05
      threshold: 1.15
```
(I preferred the faster speed of the old models, and was happy with the speed/accuracy tradeoff)

I get the error below:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-45-fe0e9c474203> in <module>
----> 1 pipeline = Pipeline.from_pretrained("speaker-diarization-config.yaml", use_auth_token=YOUR_TOKEN)

/opt/conda/lib/python3.8/site-packages/pyannote/audio/core/pipeline.py in from_pretrained(cls, checkpoint_path, hparams_file, use_auth_token, cache_dir)
    132 
    133         if "params" in config:
--> 134             pipeline.instantiate(config["params"])
    135 
    136         if hparams_file is not None:

/opt/conda/lib/python3.8/site-packages/pyannote/pipeline/pipeline.py in instantiate(self, params)
    442 
    443             msg = f"parameter '{name}' does not exist"
--> 444             raise ValueError(msg)
    445 
    446         self.initialize()

ValueError: parameter 'segmentation_onset' does not exist
```

The code previously used to run, last ran it successully around 2 months ago. I was trying to rerun it now, and realised I needed to add the use_auth_token (and accept the models), but now I get the error above.

**Comment by laphang** [comment]
Closing this now, was able to get it working by moving to the latest pipeline yaml file and making tweaks from there. 

```
pipeline:
  name: pyannote.audio.pipelines.SpeakerDiarization
  params:
    clustering: AgglomerativeClustering
    #embedding: speechbrain/spkrec-ecapa-voxceleb
    embedding: pyannote/embedding
    embedding_batch_size: 32
    embedding_exclude_overlap: true
    segmentation: pyannote/segmentation@2022.07
    segmentation_batch_size: 32

params:
  clustering:
    method: centroid
    min_cluster_size: 15
    threshold: 0.7153814381597874
  segmentation:
    min_duration_off: 0.5817029604921046
    threshold: 0.4442333667381752
```
