### ISSUE TITLE
Cannot run diarization in offline mode (help pls)

### ISSUE THREAD

**Issue by matiasvergaras** [pyannote/pyannote-audio#1294]
Hello,

I'm trying to run diarization in offline mode, following the instructions in the [applying a pipeline](https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/applying_a_pipeline.ipynb) tutorial. So far I have managed to run segmentation, but I can't replicate for diarization, since I don't know what to put in the 'embedding' field of its config.yaml (I need everything to go offline, not only the segmentation part). 

I have tried downloading embedding_model.ckpt from [speechbrain/spkrec-ecapa-voxceleb](https://huggingface.co/speechbrain/spkrec-ecapa-voxceleb/tree/main) and referencing it, but it didn't work: I keep receiving a 'pyannote.audio' KeyError.

**Comment by albyho** [comment]
``` yaml
pipeline:
  name: pyannote.audio.pipelines.SpeakerDiarization
  params:
    clustering: AgglomerativeClustering
    embedding: models/speechbrain/spkrec-ecapa-voxceleb/embedding_model.ckpt
    embedding_batch_size: 32
    embedding_exclude_overlap: true
    segmentation: models/pyannote/segmentation/pytorch_model@2.1.bin
    segmentation_batch_size: 32

params:
  clustering:
    method: centroid
    min_cluster_size: 15
    threshold: 0.7153814381597874
  segmentation:
    min_duration_off: 0.5817029604921046
    threshold: 0.4442333667381752
```
To use `SpeechBrainPretrainedSpeakerEmbedding`, make sure the path of "embedding" contains the string "speechbrain". Otherwise, `PyannoteAudioPretrainedSpeakerEmbedding` will be used.
