### ISSUE TITLE
SpeakerDiarization in offline mode can't work 

### ISSUE THREAD

**Issue by maxoo1001** [pyannote/pyannote-audio#1554]
When I use the SpeakerDiarization feature offline, I find that version 3.1 runs very slowly, and there are frequent memory errors. Thus, I am considering switching to the 2.0 yaml. However, during use, I noticed that the directory structure is quite different from 3.0. I have already referred to issues #1427 and #1294, but I still encounter errors. Could you help me identify the problem?

# directory:
D:\Code\models\pyannote\config.yaml
D:\Code\models\pyannote\models--pyannote--segmentation
D:\Code\models\pyannote\speechbrain\spkrec-ecapa-voxceleb

# D:\Code\models\pyannote\config.yaml
pipeline:
  name: pyannote.audio.pipelines.SpeakerDiarization
  params:
    clustering: AgglomerativeClustering
    embedding: D:/Code/models/pyannote2/speechbrain/spkrec-ecapa-voxceleb
    embedding_batch_size: 32
    embedding_exclude_overlap: true
    segmentation: D:/Code/models/pyannote2/models--pyannote--segmentation/pytorch_model.bin
    segmentation_batch_size: 32

# D:\Code\models\pyannote\speechbrain\spkrec-ecapa-voxceleb\hyperparams.yaml
#Pretrain folder (HuggingFace)
pretrained_path: D:/Code/models/pyannote2/speechbrain/spkrec-ecapa-voxceleb

# error
  File "D:\conda_env\envs\py\lib\site-packages\pyannote\audio\core\pipeline.py", line 136, in from_pretrained
    pipeline = Klass(**params)
  File "D:\conda_env\envs\py\lib\site-packages\pyannote\audio\pipelines\speaker_diarization.py", line 169, in __init__
    self._embedding = PretrainedSpeakerEmbedding(
  File "D:\conda_env\envs\py\lib\site-packages\pyannote\audio\pipelines\speaker_verification.py", line 749, in PretrainedSpeakerEmbedding
    return PyannoteAudioPretrainedSpeakerEmbedding(
  File "D:\conda_env\envs\py\lib\site-packages\pyannote\audio\pipelines\speaker_verification.py", line 655, in __init__
    self.model_: Model = get_model(self.embedding, use_auth_token=use_auth_token)
  File "D:\conda_env\envs\py\lib\site-packages\pyannote\audio\pipelines\utils\getter.py", line 75, in get_model
    model = Model.from_pretrained(
  File "D:\conda_env\envs\py\lib\site-packages\pyannote\audio\core\model.py", line 624, in from_pretrained
    path_for_pl = hf_hub_download(
  File "D:\conda_env\envs\py\lib\site-packages\huggingface_hub\utils\_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "D:\conda_env\envs\py\lib\site-packages\huggingface_hub\utils\_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'D:/Code/models/pyannote2/speechbrain/spkrec-ecapa-voxceleb'. Use `repo_type` argument if needed.

**Comment by maxoo1001** [comment]
Translation: Solved... It was a path issue.

**Comment by WhXmURandom** [comment]
> Solved... It was a path issue.

Hello, I also encountered the same issue. May I ask how you resolved it?

**Comment by wwfcnu** [comment]
> Solved... It was a path issue.

请问你是怎么解决的

**Comment by wwfcnu** [comment]
> > Solved... It was a path issue.
> 
> Hello, I also encountered the same issue. May I ask how you resolved it?

你解决了这个问题吗

**Comment by wwfcnu** [comment]
> Solved... It was a path issue.

还需要修改哪里的路径呢

**Comment by rondinellimorais** [comment]
`config.yaml`
```yaml
version: 3.1.0
pipeline:
  name: pyannote.audio.pipelines.SpeakerDiarization
  params:
    clustering: AgglomerativeClustering
    embedding: /Users/rondinellimorais/speechbrain/spkrec-ecapa-voxceleb # 1) relative path speechbrain dir
    embedding_batch_size: 32
    embedding_exclude_overlap: true
    segmentation: /Users/rondinellimorais/pyannote/models--pyannote--segmentation-3.0/pytorch_model.bin # 2) download pytorch_model.bin from HuggingFace
    segmentation_batch_size: 32
params:
  clustering:
    method: centroid
    min_cluster_size: 12
    threshold: 0.7045654963945799
  segmentation:
    min_duration_off: 0.0
```

`/Users/rondinellimorais/speechbrain`

<img width="349" alt="image" src="https://github.com/user-attachments/assets/70b7e3d0-b57d-4d61-8a90-1150e1d230f1">

Edit your `/Users/rondinellimorais/speechbrain/spkrec-ecapa-voxceleb/hyperparams.yaml` specify the model path

```yaml
# Pretrain folder (HuggingFace)
pretrained_path: /Users/rondinellimorais/speechbrain/spkrec-ecapa-voxceleb # 3) same path as config embedding in config.yaml
....
```

Finally

```python
from pyannote.audio import Pipeline, Model
pipeline = Pipeline.from_pretrained('config.yaml')
pipeline
```
