### ISSUE TITLE
Issue in offline use of speaker-diarization 3.1 model

### ISSUE THREAD

**Issue by ashu5644** [pyannote/pyannote-audio#1599]
@hbredin , I am trying to use speaker-diarization 3.1 model in offline mode , but I am getting following error:

```
sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from /home/ubuntu/workspace/pyannote_models/pyannote-wespeaker-voxceleb-resnet34-LM-embedding.bin failed:Protobuf parsing failed.
```

Code:
```
pipeline = Pipeline.from_pretrained('config.yaml')
pipeline.to('cuda')
audio_, _ = librosa.load('audio.wav', sr=16000)
audio = {"waveform": torch.tensor(np.reshape(audio_,(1,-1))), "sample_rate": 16000}
output = pipeline(audio)
```

config.yaml:
```

version: 3.1.0

pipeline:
  name: pyannote.audio.pipelines.SpeakerDiarization
  params:
    clustering: AgglomerativeClustering
    embedding: '/home/ubuntu/workspace/pyannote-wespeaker-voxceleb-resnet34-LM-embedding.bin'
    embedding_batch_size: 32
    embedding_exclude_overlap: true
    segmentation: '/home/ubuntu/workspace/pyannote_models/pyannote-segmentation-3.0-pytorch-model.bin'
    segmentation_batch_size: 32

params:
  clustering:
    method: centroid
    min_cluster_size: 12
    threshold: 0.7045654963945799
  segmentation:
    min_duration_off: 0.0

```
Similar code is working for speaker-diarization 3.0 in offline mode by replacing embedding argument in corresponding config with .onnx model path. But for speaker-diarization 3.1 no .onnx model exists [here](https://huggingface.co/pyannote/wespeaker-voxceleb-resnet34-LM/tree/main). Can you please suggest some workaround for this issue ? 

Thank you.
