### ISSUE TITLE
After fine-tuning with MagicData-RAMC dataset，i test on Aishell-4 dadaset DER increased.

### ISSUE THREAD

**Issue by Arnold134777** [pyannote/pyannote-audio#1738]
### Tested versions

3.1.1

### System information

CentOS -pyannote.audio 3.1.1

### Issue description

Hi, after fine-tuning with MagicData-RAMC dataset DER decrease from 20.1% to 11.7%.

But test on Aishell-4 dadaset DER increase from 10.9% -> 15.4%.

Any suggestions on how to fine-tune without affecting the original dataset DER or improve original dataset performance？

**Comment by FrenchKrab** [comment]
If you don't want your model to forget about the previous data (="catastrophic forgetting"), one solution can be to keep the previous data in its training.
To do that you can create a meta-protocol in your pyannote-database yaml file.
For example:

```yml

Protocols:
  X:
    SpeakerDiarization:
      RamcAndAishell:
        train:
          RAMC.SpeakerDiarization.Full: [train]
          AISHELL4.SpeakerDiarization.Full: [train]
        development:
          RAMC.SpeakerDiarization.Full: [development]
          AISHELL4.SpeakerDiarization.Full: [development]
 ```
 
 Additionally when you create your task, you can pass
 ```python
 task = SpeakerDiarization(...., balance=["database"])
 ```
so that your model sees all datasets in the same proportion, which can be useful if one dataset is much longer than the other.
