### ISSUE TITLE
Domain Classification Validate does not output correctly in params.yml 

### ISSUE THREAD

**Issue by Mymoza** [pyannote/pyannote-audio#198]
When running `pyannote-domain-classification validate --gpu --to=1000 --every=10 ${TRAIN_DIR} AMI.SpeakerDiarization.MixHeadset --subset=development --chronological`, I had the following in `params.yml` : 

```
cat pyannote-AMI/domain_classification/train/AMI.SpeakerDiarization.MixHeadset.train/validate/AMI.SpeakerDiarization.MixHeadset.development/params.yml
accuracy: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - f8
  - 0
  - 1
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  AAAAAAAA8D8=
epoch: 10
``` 

It should be actual accuracy numbers instead of weird things.
