### ISSUE TITLE
Negative coverage percentage for speaker embedding validation

### ISSUE THREAD

**Issue by prlabu** [pyannote/pyannote-audio#244]
When I'm validating a `pyannote-speaker-embedding` model on AMI, it shows a negative percentage (`coverage@0.90purity | Epoch #20 = -21.6651% (best) | Epoch #68 = -21.6651%: : 14iteration [26:12:03, 6417.73s/iteration]`) for coverage. Something tells me a negative value for the percentage shouldn't be possible -- is that normal?

The tutorial doesn't say what the params file should look like by the end of validation. Here's mine currently...
`$ cat ${VALIDATE_DIR}/AMI.SpeakerDiarization.MixHeadset.development/params.yml`
```
coverage@0.90purity: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - f8
  - 0
  - 1
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  GKNDjDa7y78=
epoch: 20
```
