### ISSUE TITLE
For Domain Classification, where is the Domain label supposed to come from?

### ISSUE THREAD

**Issue by geniki** [pyannote/pyannote-audio#251]
Thanks for adding this great functionality.

One way I can see is adding the domain label in `mdtm`/`uem` file and then adding it to `current_file` [here](https://github.com/pyannote/pyannote-db-odessa-ami/blob/master/AMI/__init__.py#L82).

However, this would require editing the database plugin for every dataset. If I just wanted to assign a few datasets (e.g. AMI and LibriSpeech) to domain A and some others (e.g. VoxCelebs) to domain B, is there an easier way without editing their individual database plugins?

**Comment by hbredin** [comment]
[Custom protocols](https://github.com/pyannote/pyannote-database#custom-protocols) supports a [`domain`](https://github.com/pyannote/pyannote-database#domain) keyword -- but this assumes that you are not using `pyannote.database` plugins.

If you do use `pyannote.database` plugins, one way of doing it would be to define a preprocessor in the configuration file `config.yml` like this:

```yaml
preprocessors:
  domain:
    name: your_package.your_module.YourDomainProviderClass
    params:
      AMI: A
      LibriSpeech: A
      VoxCeleb: B
```

and then implement the class `your_package.your_module.YourDomainProviderClass` like this (warning: untested pseudo-code):

```python
class YourDomainProviderClass:
  def __init__(self, **params):
    self.params = params

  def __call__(self, current_file):
    return self.params[current_file['database']]
```
