### ISSUE TITLE
Simple diarization with Python

### ISSUE THREAD

**Issue by nshmyrev** [pyannote/pyannote-audio#312]
I was kind of missing this simple script to actually run diarization on a file:

```
#!/usr/bin/python3 

import sys

inputfn = sys.argv[1]
outputfn = sys.argv[2]

from pyannote.audio.pipeline.speaker_diarization import SpeakerDiarization

test_file = {'uri': 'filename', 'audio': inputfn}

diarization = SpeakerDiarization(sad_scores='sad_dihard', scd_scores='scd_dihard', embedding='emb_voxceleb', metric='cosine', method='affinity_propagation')
diarization.load_params("params.yml")

turns = diarization(test_file)
with open(outputfn, 'w') as fp:
     turns.write_rttm(fp)
```
With params.yml file like this:

```
params:
  min_duration: 3.9939244408136276
  speech_turn_assignment:
    closest_assignment:
      threshold: 1.3786317920460274
  speech_turn_clustering:
    clustering:
      damping: 0.9231549395773737
      preference: -1.571915891387201
  speech_turn_segmentation:
    speaker_change_detection:
      alpha: 0.08296024595899683
      min_duration: 0.40446309879155706
    speech_activity_detection:
      min_duration_off: 0.6857137236312955
      min_duration_on: 0.3225952679776678
      offset: 0.9436397097473367
      onset: 0.704966228813754
      pad_offset: 0.08311274833799132
      pad_onset: 0.06505433882746965
```

Not sure where to put it in the docs though.
