### ISSUE TITLE
Output of Speaker Change Detection

### ISSUE THREAD

**Issue by couch-potahto** [pyannote/pyannote-audio#322]
Hi @hbredin , I was just wondering if I could have more information on the output of the Speaker Change Detection component? 
I'm referring to the npy files that are created after the Speaker Change Detection is applied to the test files. From my initial analysis I can see that the output is a numpy array holding arrays of 2 elements each but I can't seem to find any information on what the 2 numbers correspond to.

Thank you for your help!

**Comment by hbredin** [comment]
The `metadata.yml` file at the root of the `apply` directory contains the information you are looking for:

```yaml
# example of content of metadata.yml
classes:
  - non_change
  - change
dimension: 2
duration: 0.0203125
start: 0.0
step: 0.0016875
```

Dimension #1 is `non_change` log-probability, dimension #2 is `change` log-probability.
You get one score every 1.6875ms (`step`) that indicates whether a speaker change occurs during a 20.3125ms window (`duration`) centered on current time step.

Within `pyannote.audio`, those `npy` files are wrapped in a `pyannote.audio.features.Precomputed` instance that provides convenient method to access their content.
