### ISSUE TITLE
 Precomputed features fail at the `validation` stage

### ISSUE THREAD

**Issue by ahogg** [pyannote/pyannote-audio#375]
I run into an error at the validation stage on the development set when using precomputed features but I am not quite sure why.

I have followed the [data_preparation](https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/data_preparation) and [feature_extraction](https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/feature_extraction) tutorials. 

When I run, for example,  `pyannote-audio sad train --subset=train --to=10 --parallel=4 ${EXP_DIR} AMI.SpeakerDiarization.MixHeadset` the model trains fine:

```
Training set: 118it [00:09, 12.79it/s]
Training: 100%|█████████████████████████████| 10/10 [58:11<00:00, 349.18s/epoch]
```

However, when I then run `pyannote-audio sad validate --subset=development --from=1 --to=10 --every=2 ${TRN_DIR} AMI.SpeakerDiarization.MixHeadset` as per the tutorial, I get the following error:

> pyannote-audio sad validate --subset=development --from=1 --to=10 --every=2 ${TRN_DIR} AMI.SpeakerDiarization.MixHeadset
> 0iteration [00:00, ?iteration/s]Traceback (most recent call last):
>   File "/home/ahogg/anaconda3/envs/pyannote/bin/pyannote-audio", line 11, in <module>
>     load_entry_point('pyannote.audio', 'console_scripts', 'pyannote-audio')()
>   File "/home/ahogg/anaconda3/envs/pyannote/lib/python3.8/site-packages/pyannote/audio/applications/pyannote_audio.py", line 422, in main
>     app.validate(protocol, **params)
>   File "/home/ahogg/anaconda3/envs/pyannote/lib/python3.8/site-packages/pyannote/audio/applications/base.py", line 350, in validate
>     details = self.validate_epoch(
>   File "/home/ahogg/anaconda3/envs/pyannote/lib/python3.8/site-packages/pyannote/audio/applications/speech_detection.py", line 67, in validate_epoch
>     pretrained = Pretrained(
>   File "/home/ahogg/anaconda3/envs/pyannote/lib/python3.8/site-packages/pyannote/audio/features/pretrained.py", line 107, in __init__
>     augmentation=augmentation, sample_rate=self.feature_extraction_.sample_rate
> AttributeError: 'Precomputed' object has no attribute 'sample_rate'
> 0iteration [00:00, ?iteration/s]

The configuration file ( `cat ${EXP_DIR}/config.yml`) defining the experimental setup is as follows: 
```
task:
   name: SpeechActivityDetection
   params:
      duration: 2.0
      batch_size: 64
      per_epoch: 1

feature_extraction:
   name: Precomputed
   params:
      root_dir: tutorials/feature_extraction

architecture:
    name: pyannote.audio.models.PyanNet
    params:
        sincnet:
            skip: True
        rnn:
            unit: LSTM
            hidden_size: 128
            num_layers: 2
            bidirectional: True
        ff:
            hidden_size: [128, 128]

name: ConstantScheduler
   params:
      learning_rate: 0.01
```
Any advice on what I am doing wrong would be greatly appreciated. Thanks!
