### ISSUE TITLE
Training SAD data with chime6 dataset

### ISSUE THREAD

**Issue by sangeetaghangam** [pyannote/pyannote-audio#395]
I wanted to train the SAD model with Chime6 data. Is it enough to create a database.yml as below or do I need to create a new db template?

```yaml
Databases:
   CHIME6: ./audio/*/{uri}.wav
 
Protocols:
  CHIME6:
      SpeakerDiarization:
         MultiMic:
           train:
              annotation: ./chime6/train.worn.u400k.rttm
           development:
              annotation: ./chime6/dev.worn.rttm
```
