### ISSUE TITLE
ValueError exception when running sad training

### ISSUE THREAD

**Issue by aidosRepoint** [pyannote/pyannote-audio#396]
Hi,

I have followed the data preparation tutorial from the beginning to the end.
Then I started to follow the SAD training tutorial and when reaching the following part and executing it:

`$ pyannote-audio sad train --subset=train --to=200 --parallel=4 ${EXP_DIR} AMI.SpeakerDiarization.MixHeadset`

I obtain the following exception:

`user@user-desktop:~/VAD/pyannote/pyannote-audio$ pyannote-audio sad train --subset=train --to=200 --parallel=4 ${EXP_DIR} AMI.SpeakerDiarization.MixHeadset
Training set: 118it [00:08, 14.44it/s]
Traceback (most recent call last):
  File "/home/user/.local/bin/pyannote-audio", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.7/site-packages/pyannote/audio/applications/pyannote_audio.py", line 363, in main
    app.train(protocol, **params)
  File "/home/user/.local/lib/python3.7/site-packages/pyannote/audio/applications/base.py", line 192, in train
    alignment=self.model_alignment_)
  File "/home/user/.local/lib/python3.7/site-packages/pyannote/audio/labeling/tasks/speaker_change_detection.py", line 234, in get_batch_generator
    per_epoch=self.per_epoch)
  File "/home/user/.local/lib/python3.7/site-packages/pyannote/audio/labeling/tasks/speaker_change_detection.py", line 99, in __init__
    resolution=resolution, alignment=alignment, **kwargs)
  File "/home/user/.local/lib/python3.7/site-packages/pyannote/audio/labeling/tasks/base.py", line 137, in __init__
    total_duration = self._load_metadata(protocol, subset=subset)
  File "/home/user/.local/lib/python3.7/site-packages/pyannote/audio/labeling/tasks/base.py", line 309, in _load_metadata
    y = self.initialize_y(current_file)
  File "/home/user/.local/lib/python3.7/site-packages/pyannote/audio/labeling/tasks/base.py", line 209, in initialize_y
    mode='center')
ValueError: too many values to unpack (expected 2)`

**Comment by hbredin** [comment]
Looks like you are using an outdated version of pyannote.audio (or its pyannote.core dependency).

```bash
git clone https://github.com/pyannote/pyannote-audio.git
cd pyannote-audio/
pip install .
```

Please, when reporting a bug, use the provided bug template.
This will make things much easier to debug...

**Comment by aidosRepoint** [comment]
> Looks like you are using an outdated version of pyannote.audio (or its pyannote.core dependency).
> 
> ```shell
> git clone https://github.com/pyannote/pyannote-audio.git
> cd pyannote-audio/
> pip install .
> ```
> 
> Please, when reporting a bug, use the provided bug template.
> This will make things much easier to debug...

indeed, this was the reason. Thank you! Closing the issue.

**Comment by kan-cloud** [comment]
**Describe the bug**
A similar error:
"""
File "/home/ubuntu/.conda/envs/pyannote-Aug/lib/python3.7/site-packages/pyannote/database/__init__.py", line 158, in get_protocol
    database_name, task_name, protocol_name = name.split(".")
ValueError: too many values to unpack (expected 3) 
"""
appears when I attempt to validate the speaker embedding model. The pyannote/database/ file __init__.py on my system is identical to that on the pyannote-database page.

**To Reproduce**
Steps to reproduce the behavior:
Define the AMI.SpeakerDiarization.MixHeadset.train as shown in the tutorial
```bash
$ pyannote-audio export EXP_DIR=tutorials/models/speaker_embedding
$ pyannote-audio export TRN_DIR=${EXP_DIR}/train/AMI.SpeakerDiarization.MixHeadset.train
$ pyannote-audio export TRN_DIR=${EXP_DIR}/train/AMI.SpeakerDiarization.MixHeadset.train
$ pyannote-audio emb validate --subset=development --to=165 --every=5 ${TRN_DIR} AMI.SpeakerDiarization.MixHeadset.train
```

**Content of `config.yml`**

```yaml
feature_extraction:
   name: pyannote.audio.features.RawAudio
   params:
      sample_rate: 8000

architecture:
   name: pyannote.audio.models.SincTDNN
   params:
      sincnet:
         sample_rate: 8000
         stride: [5, 1, 1]
         waveform_normalize: True
         instance_normalize: True
      tdnn:
         embedding_dim: 512
      embedding:
         batch_normalize: False
         unit_normalize: False

task:
   name: AdditiveAngularMarginLoss
   params:
      margin: 0.05
      s: 10
      duration: 2.0
      per_fold: 256
      per_label: 1
      per_epoch: 5
      per_turn: 1
      label_min_duration: 30

scheduler:
   name: ConstantScheduler
   params:
      learning_rate: 0.01
```

**pyannote environment**

```bash
$ pip freeze | grep pyannote
pyannote.audio==2.0a1+60.gc683897
pyannote.core==4.1
pyannote.database==4.0.1
pyannote.metrics==3.0.1
pyannote.pipeline==1.5.2
```

**Additional context**
Add any other context about the problem here.
