### ISSUE TITLE
using ACRoPoLiS model, the task parameter

### ISSUE THREAD

**Issue by emmaducos** [pyannote/pyannote-audio#406]
**Describe the bug**
I am trying to use the ACRoPoLiS model in the branch Voice_type_classifier of pyannote-audio.
I copied all the related code of ACRoPoLis into models.py.
While trying to train on the ACRoPoLiS model found in pyannote/audio/models/models.py, I got the error : 
`TypeError: get_resolution() missing 1 required positional argument: 'task'`
Adding a task parameter in architecture.params of the config.yml file helps resolve this issue, but I can't find anywhere in the code what to put in this `task` parameter, nor do I understand the `specification` parameter.
The task is already described in the config.yml.

**To Reproduce**
```bash
$ git checkout voice_type_classifier
```
add the ACRoPoLiS class in models.py, add convolutional.py and recurrent.py in models/, add the model class in models/__init__.py
set EXP_DIR environment variable
```bash
$ pyannote-audio mlt train --subset=train --to=50 --parallel=4 ${EXP_DIR} AMI.SpeakerDiarization.MixHeadset
```

**Content of `config.yml`**

```yaml
# A multilabel detection model is trained.
# Here, training relies on 2s-long audio chunks,
# batches of 64 audio chunks, and saves model to
# disk every one (1) day worth of audio.
# The labels_spec specifies how to build the classes
# of the model given the raw label.

# Here, we consider 6 regular labels which are
# car, children, people_speaking, people_walking, 
# large_vehicle, brakes_squeaking. It will 
# account for 6 dimensions in the predicted vector. 
# This type of labels is activated whenever a utterance 
# with the label of interest is encountered in the input
# annotation.
# To sum up, our model will output a vector of 6 scores :
# [car, children, people_speaking, people_walking, large_vehicle, brakes_squeaking]
task:
   name: MultilabelDetection
   params:
      duration: 2.0
      batch_size: 64
      per_epoch: 1
      labels_spec:
        regular: ['car', 'children', 'people_speaking', 'people_walking', 'large_vehicle', 'brakes_squeaking']

# Data augmentation is applied during training.
# Here, it consists in additive noise from the
# MUSAN database, with random signal-to-noise
# ratio between 5 and 20 dB
data_augmentation:
   name: AddNoise
   params:
      snr_min: 5
      snr_max: 20
      collection: MUSAN.Collection.BackgroundNoise

feature_extraction:
   name: LibrosaMFCC
   params:
      e: False 
      De: True
      DDe: True
      coefs: 19
      D: True
      DD: True
      duration: 0.025
      step: 0.010
      sample_rate: 44100

architecture:
   name: pyannote.audio.models.ACRoPoLiS
   params:
      task: MultilabelDetection
      convolutional:
         n_features: 1
         sample_rate: 44100
         instance_normalize: False
         dropout: 0.5

# We use a constant learning rate of 1e-2
scheduler:
   name: ConstantScheduler
   params:
      learning_rate: 0.01
```

**pyannote environment**

```bash
pyannote.audio===JSALT-v5-327.gc08c7f1
pyannote.core==3.7.1
pyannote.database==3.0.1
pyannote.db.musan==0.1.3
pyannote.metrics==3.0
pyannote.pipeline==1.5
```

**Additional context**
I am trying to implement a DCASE 2017 paper starting from the architecture off the ACRoPoLiS model, which seems to be the closest.
