### ISSUE TITLE
Unable to rum the training step of the speaker diarization pipeline tutorial

### ISSUE THREAD

**Issue by kan-cloud** [pyannote/pyannote-audio#408]
**Describe the bug**
When I try to run the following step:
pyannote-pipeline train --subset=development --forever ${EXP_DIR} AMI.SpeakerDiarization.MixHeadset
I get the error
raise PyannoteFeatureExtractionError(msg)
pyannote.audio.features.precomputed.PyannoteFeatureExtractionError: Directory /home/ubuntu/kanishk_speaker_diarization/pyannote-audio/tutorials/pipelines/speaker_diarization/sad_ami does not contain precomputed features for file "ES2003a.Mix-Headset" of "AMI" database.

**To Reproduce**
start from the pyannote-audio directory
```bash
$ export EXP_DIR=tutorials/pipelines/speaker_diarization
$ for SUBSET in developement test
 > do
 > for TASK in sad scd emb
 >  do
 >    pyannote-audio ${TASK} apply --step=0.1 --pretrained=${TASK}_ami --subset=${SUBSET} ${EXP_DIR} AMI.SpeakerDiarization.MixHeadset    
 >  done
 > done

$ pyannote-pipeline train --subset=development --forever ${EXP_DIR} AMI.SpeakerDiarization.MixHeadset
```

**Content of `config.yml`**

```yaml
pipeline:
  name: pyannote.audio.pipeline.speaker_diarization.SpeakerDiarization
  params:
    # replace {{EXP_DIR}} by its actual value
    sad_scores: tutorials/pipelines/speaker_diarization/sad_ami
    scd_scores: tutorials/pipelines/speaker_diarization/scd_ami
    embedding: tutorials/pipelines/speaker_diarization/emb_ami
    method: affinity_propagation

# one can freeze some of the hyper-parameters
# for instance, in this example, we are using
# hyper-parameters obtained in the speech 
# actitivy detection pipeline tutorial
freeze:
  speech_turn_segmentation:
    speech_activity_detection:
      min_duration_off: 0.6315121069334447
      min_duration_on: 0.0007366523493967721
      offset: 0.5727193137037349
      onset: 0.5842225805454029
      pad_offset: 0.0
      pad_onset: 0.0
```

**pyannote environment**

```bash
$ pip freeze | grep pyannote
pyannote.audio==2.0.a
pyannote.core==3.7.1
pyannote.database==3.0.1
pyannote.db.musan==0.1.3
pyannote.db.voxceleb==1.0.1
pyannote.metrics==2.3
pyannote.pipeline==1.5
```

**Additional context**
