### ISSUE TITLE
Speaker embedding validation not running to completion even after 2 days on a GPU.  

### ISSUE THREAD

**Issue by kan-cloud** [pyannote/pyannote-audio#414]
**Describe the bug**
Speaker embedding validation not running to completion even after 2 days on a GPU.  

Final terminal error:
approximated by [0, audio duration].
  warnings.warn(msg)
diarization_fscore | Epoch #1 = 86.0978% (best) | Epoch #3 = 84.9364%: : 2iteration [00:05,  3.20s/iteration]Killed
**To Reproduce**
After following data preparation tutorial I ran the embedding pipeline on the AMI dataset as I didn't know how to obtain the 
VoxCeleb dataset (is this the reason?). The following steps start in the pyannote-audio directory just like in the tutorial.
```bash
$ export EXP_DIR=tutorials/models/speaker_embedding
$ pyannote-audio emb train --subset=train --to=4 --parallel=4 ${EXP_DIR} AMI.SpeakerDiarization.MixHeadset
$ export TRN_DIR=tutorials/models/speaker_embedding/train/AMI.SpeakerDiarization.MixHeadset.train
$ pyannote-audio emb validate --subset=test --to=4 --every=2 ${TRN_DIR} AMI.SpeakerDiarization.MixHeadset
```

**Content of `config.yml`**

```yaml

feature_extraction:
   name: pyannote.audio.features.RawAudio
   params:
      sample_rate: 16000

data_augmentation:
   name: pyannote.audio.augmentation.noise.AddNoise
   params:
     snr_min: 5
     snr_max: 15
     collection:
       - MUSAN.Collection.BackgroundNoise
       - MUSAN.Collection.Music

architecture:
   name: pyannote.audio.models.SincTDNN
   params:
      sincnet:
         stride: [5, 1, 1]
         waveform_normalize: True
         instance_normalize: True
      tdnn:
         embedding_dim: 512
      embedding:
         batch_normalize: False
         unit_normalize: False

task:
   name: AdditiveAngularMarginLoss
   params:
      margin: 0.05
      s: 10
      duration: 2.0
      per_fold: 256
      per_label: 1
      per_epoch: 5
      per_turn: 1
      label_min_duration: 30

scheduler:
   name: ConstantScheduler
   params:
      learning_rate: 0.01
```

**pyannote environment**

```bash
$ pip freeze | grep pyannote
pyannote.audio==2.0.a
pyannote.core==3.7.1
pyannote.database==3.0.1
pyannote.db.musan==0.1.3
pyannote.db.voxceleb==1.0.1
pyannote.metrics==2.3
pyannote.pipeline==1.5
```

**Additional context**
Here's the terminal content for when the process was running for 3 days till it was 'Killed':
pyannote-audio emb validate --subset=test --to=4 --every=2 ${TRN_DIR} AMI.SpeakerDiarization.MixHeadset
/home/ubuntu/.local/lib/python3.6/site-packages/pyannote/database/database.py:51: UserWarning: Ignoring deprecated 'preprocessors' argument in MUSAN.__init__. Pass it to 'get_protocol' instead.
  warnings.warn(msg)                                                                                                    /home/ubuntu/.local/lib/python3.6/site-packages/pyannote/audio/embedding/approaches/arcface_loss.py:170: FutureWarning: The 's' parameter is deprecated in favor of 'scale', and will be removed in a future release
  warnings.warn(msg, FutureWarning)                                                                                     0iteration [00:00, ?iteration/s]/home/ubuntu/.local/lib/python3.6/site-packages/pyannote/audio/embedding/approaches/arcface_loss.py:170: FutureWarning: The 's' parameter is deprecated in favor of 'scale', and will be removed in a future release
  warnings.warn(msg, FutureWarning)
/home/ubuntu/.local/lib/python3.6/site-packages/pyannote/database/protocol/protocol.py:128: UserWarning: Existing key "annotation" may have been modified.
  warnings.warn(msg.format(key=key))                                                                                    /home/ubuntu/.local/lib/python3.6/site-packages/pyannote/database/util.py:241: UserWarning: "annotated" was approximated by [0, audio duration].
  warnings.warn(msg)
diarization_fscore | Epoch #1 = 86.0978% (best) | Epoch #3 = 84.9364%: : 2iteration [00:05,  3.20s/iteration]Killed

I noticed there was no '--from' option used in the embedding tutorial validation command:
pyannote-audio emb validate --subset=test --to=250 --every=5 ${TRN_DIR} VoxCeleb.SpeakerDiarization.VoxCeleb1
like in the other tutorials:
pyannote-audio sad validate --subset=development --from=10 --to=200 --every=10 ${TRN_DIR} AMI.SpeakerDiarization.MixHeadset
Could that be the reason?
