### ISSUE TITLE
IndexError when validating SAD

### ISSUE THREAD

**Issue by hbredin** [pyannote/pyannote-audio#435]
I did the same thing, but now, when I try to run validation on SAD, I get this error:

Feature extraction: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 232/232 [01:23<00:00,  2.79it/s]
0iteration [00:00, ?iteration/s]Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/thesis/bin/pyannote-audio", line 11, in <module>
    load_entry_point('pyannote.audio', 'console_scripts', 'pyannote-audio')()
  File "/home/ubuntu/pyannote-audio/pyannote/audio/applications/pyannote_audio.py", line 422, in main
    app.validate(protocol, **params)
  File "/home/ubuntu/pyannote-audio/pyannote/audio/applications/base.py", line 362, in validate
    **kwargs,
  File "/home/ubuntu/pyannote-audio/pyannote/audio/applications/speech_detection.py", line 77, in validate_epoch
    current_file["scores"] = pretrained(current_file)
  File "/home/ubuntu/pyannote-audio/pyannote/audio/features/base.py", line 152, in __call__
    features = self.get_features(y.data, sample_rate)
  File "/home/ubuntu/pyannote-audio/pyannote/audio/features/pretrained.py", line 232, in get_features
    progress_hook=self.progress_hook,
  File "/home/ubuntu/pyannote-audio/pyannote/audio/train/model.py", line 500, in slide
    data[indices] += fX_
IndexError: index 32834 is out of bounds for axis 0 with size 32834
0iteration [02:37, ?iteration/s]

I really don't know what could be going wrong :( any ideas @hbredin @alamnasim ?

_Originally posted by @alfonsozunigaj in https://github.com/pyannote/pyannote-audio/issues/375#issuecomment-673629154_

**Comment by hbredin** [comment]
Can you please check that you still get the error with the latest version of `pyannote.audio` (`develop`) and `pyannote.database 4.0.1 ` ?

**Comment by aidosRepoint** [comment]
Hi!

I obtain the same error when validating a model trained on MFCCs.
```
  File "/home/user/.local/lib/python3.7/site-packages/pyannote/audio/train/model.py", line 500, in slide
    data[indices] += fX_
IndexError: index 2066 is out of bounds for axis 0 with size 2066
```

my ```specs.yml``` now look as this:
```
X:
  dimension: 59 # feat.dimensions are (512, 59)
database:
  classes:
  - REPOINT
subset:
  classes:
  - train
task: frame-wise multi-class classification
y:
  classes:
  - non_speech
  - speech
```
The ```config.yml``` is:
```
architecture:
  name: pyannote.audio.models.PyanNet
  params:
    sincnet:
      skip: true
    ff:
      hidden_size:
      - 128
      - 128
      - 128
    rnn:
      bidirectional: true
      hidden_size: 128
      num_layers: 3
      unit: LSTM
feature_extraction:
   name: LibrosaMFCC
   params:
      e: False 
      De: True
      DDe: True
      coefs: 19
      D: True
      DD: True
      duration: 0.025
      step: 0.010
      sample_rate: 16000
scheduler:
  name: ConstantScheduler
  params:
    learning_rate: 0.01
task:
  name: SpeechActivityDetection
  params:
    batch_size: 32
    duration: 2.0
    per_epoch: 1
```

Is there any way of solving the issue without switching to the version on develop? For instance by tweaking the underlying code somehow.
