### ISSUE TITLE
ValueError: too many values to unpack (expected 3)

### ISSUE THREAD

**Issue by hbredin** [pyannote/pyannote-audio#438]
**Describe the bug**
A similar error:
"""
File "/home/ubuntu/.conda/envs/pyannote-Aug/lib/python3.7/site-packages/pyannote/database/__init__.py", line 158, in get_protocol
    database_name, task_name, protocol_name = name.split(".")
ValueError: too many values to unpack (expected 3) 
"""
appears when I attempt to validate the speaker embedding model. The pyannote/database/ file __init__.py on my system is identical to that on the pyannote-database page.

**To Reproduce**
Define the AMI.SpeakerDiarization.MixHeadset.train as shown in the tutorial
```bash
$ pyannote-audio export EXP_DIR=tutorials/models/speaker_embedding
$ pyannote-audio export TRN_DIR=${EXP_DIR}/train/AMI.SpeakerDiarization.MixHeadset.train
$ pyannote-audio export TRN_DIR=${EXP_DIR}/train/AMI.SpeakerDiarization.MixHeadset.train
$ pyannote-audio emb validate --subset=development --to=165 --every=5 ${TRN_DIR} AMI.SpeakerDiarization.MixHeadset.train
```

**Content of `config.yml`**

```yaml
feature_extraction:
   name: pyannote.audio.features.RawAudio
   params:
      sample_rate: 8000

architecture:
   name: pyannote.audio.models.SincTDNN
   params:
      sincnet:
         sample_rate: 8000
         stride: [5, 1, 1]
         waveform_normalize: True
         instance_normalize: True
      tdnn:
         embedding_dim: 512
      embedding:
         batch_normalize: False
         unit_normalize: False

task:
   name: AdditiveAngularMarginLoss
   params:
      margin: 0.05
      s: 10
      duration: 2.0
      per_fold: 256
      per_label: 1
      per_epoch: 5
      per_turn: 1
      label_min_duration: 30

scheduler:
   name: ConstantScheduler
   params:
      learning_rate: 0.01
```

**pyannote environment**

```bash
$ pip freeze | grep pyannote
pyannote.audio==2.0a1+60.gc683897
pyannote.core==4.1
pyannote.database==4.0.1
pyannote.metrics==3.0.1
pyannote.pipeline==1.5.2
```

**Additional context**

_Originally posted by @kan-cloud in https://github.com/pyannote/pyannote-audio/issues/396#issuecomment-688266103_
