### ISSUE TITLE
How to use other features in this project

### ISSUE THREAD

**Issue by bbrookie** [pyannote/pyannote-audio#465]
First of all thank you for your willingness to open source such an excellent project，My problem is that I see that you have provided the `with_librosa.py` file. If I want to use features such as mfcc, how can I define the feature_extraction part in `config.yml` to enable me to extract mfcc features from the sad, scd, and emb models, Instead of using SincNet to extract features from the original audio.

Looking forward to your answer, thank you.

**Comment by aidosRepoint** [comment]
I see that the issue is closed, but probably for some of the users this might be useful:

There is a parameter that you can set in the config.yml - sincnet / skip: true.

As far as I understood, it replaces the sincnet feature extraction with that, set in your config.yml. For instance, in my case it was:

```
architecture:
  name: pyannote.audio.models.PyanNet
  params:
    sincnet:
      skip: true
    ff:
      hidden_size:
      - 128
      - 128
      - 128
    rnn:
      bidirectional: true
      hidden_size: 128
      num_layers: 3
      unit: LSTM
feature_extraction:
   name: LibrosaMFCC
   params:
      e: False 
      De: True
      DDe: True
      coefs: 19
      D: True
      DD: True
      duration: 0.025
      step: 0.010
      sample_rate: 16000
scheduler:
  name: ConstantScheduler
  params:
    learning_rate: 0.01
task:
  name: SpeechActivityDetection
  params:
    batch_size: 32
    duration: 2.0
    per_epoch: 1
```
You can use one of these features - LibrosaMFCC / LibrosaMelSpectrogram / LibrosaSpectrogram.

Hope this helps.
