### ISSUE TITLE
"database" recipe output is broken

### ISSUE THREAD

**Issue by hbredin** [pyannote/pyannote-audio#970]
To check that the files created by the scripts are OK, you can use something like that

```bash
PYANNOTE_DATABASE_CONFIG=/path/to/generated/database.yml pyannote-database protocol
```

It should NOT complain and should output the list of protocols.

Then, you can further check that the statistics are correct by running
```bash
PYANNOTE_DATABASE_CONFIG=/path/to/generated/database.yml pyannote-database info Database.SpeakerDiarization.upTo_blahblah
```

Same: it should NOT complain

**Comment by J-Petiot** [comment]
The only suspicious ouput I got is :
`UserWarning: Ignoring 'BIGBANG.SpeakerDiarization.upTo_12-05-2022_10-25-30.Train' found in configuration.yml because 'Train' entries are not supported yet.                                                                                                                                                                                                                                  warnings.warn(msg)  `

Should I change Train with something else ?

**Comment by hbredin** [comment]
Yes. It should be `train`. 

Once changed, `pyannote-database info` will then complain about not finding files (at least it does on my side)

**Comment by J-Petiot** [comment]
I got this with "train" instead of "Train" :
`train                                                                                                                                                                                                                                           1 files                                                                                                                                                                                                                                      0h00m annotated                                                                                                                                                                                                                              0h00m of speech (62%)                                                                                                                                                                                                                        3 speakers `

**Comment by hbredin** [comment]
OK, weird. Can you let me know what commands you ran exactly?

```bash
prodigy pyannote.database XXX
PYANNOTE_DATABASE_CONFIG=XXX pyannote-database info XXX 
```

**Comment by J-Petiot** [comment]
`prodigy pyannote.database newdata DATABASE /home/jpetiot/work/database/`
And:
`PYANNOTE_DATABASE_CONFIG=/home/jpetiot/work/database/configuration.yml pyannote-database info DATABASE.SpeakerDiarization.upTo_12-05-2022_14-30-24`

**Comment by hbredin** [comment]
Can you share the output of `ls  /home/jpetiot/work/database/` and `cat /home/jpetiot/work/database/configuration.yml`?

**Comment by J-Petiot** [comment]
After pyannote.database there is :
`configuration.yml  upTo_12-05-2022_14-30-24.lst  upTo_12-05-2022_14-30-24.rttm  upTo_12-05-2022_14-30-24.uem `
in /database
and configuration.yml:

```
Databases:
    DATABASE: /home/jpetiot/work/diarization/corpus/{uri}.wav
Protocols:
    DATABASE:
        SpeakerDiarization:
            upTo_12-05-2022_14-30-24:
                train:
                    annotated: upTo_12-05-2022_14-30-24.uem
                    annotation: upTo_12-05-2022_14-30-24.rttm
                    uri: upTo_12-05-2022_14-30-24.lst
```
